Proyecto_NoSQL/Proyecto_NoSQL/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using Proyecto.Logic.Conexion;
using Proyecto.Model.MisModelos;

namespace Proyecto_NoSQL.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            ///Cliente clientes;
            ///

            var laConexion = new Clientes();
            List<Cliente> clientes = new List<Cliente>();
            clientes = laConexion.FindClientesAsDocuments("proyectoDb", "clientes_bson");


            return View(clientes);
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            var laConexion = new Clientes();
            Cliente cliente = laConexion.FindClienteDocument("proyectoDb", "clientes_bson", id);
          
            return View(cliente);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        public ActionResult Create(Cliente cliente,string tipoTef,string numeroTef)
        {
            if (cliente != null)
            {
                try
                {
                    List<Telefono> nuevosTelef = new List<Telefono>();
                    Telefono[] telefonoExistentes = cliente.Telefonos;
                    if (telefonoExistentes!=null)
                    {
                        List<Telefono> telefonoExistentesList = telefonoExistentes.ToList();
                        nuevosTelef = telefonoExistentesList;
                        nuevosTelef.Add(new Telefono(tipoTef, numeroTef));
                    }
                    else
                    {
                        nuevosTelef.Add(new Telefono(tipoTef, numeroTef));
                    }

                    cliente.Telefonos= nuevosTelef.ToArray();

                     BsonDocument[] clienteNuevo = new BsonDocument[] { cliente.ToBsonDocument() };

                    var laConexion = new Clientes();
                    laConexion.Insert<BsonDocument>(clienteNuevo, "proyectoDb", "clientes_bson");

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
            else { return View(); }

        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            var laConexion = new Clientes();
            Cliente cliente = laConexion.FindClienteDocument("proyectoDb", "clientes_bson", id);
            TempData["telefonos"]=cliente.Telefonos;
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Cliente cliente, string tipoTef, string numeroTef)
        {
            try
            {
                
                List<Telefono> nuevosTelef = new List<Telefono>();
                Telefono[] telefonoExistentes = (Telefono[])TempData["telefonos"];
                if (telefonoExistentes != null)
                {
                    List<Telefono> telefonoExistentesList = telefonoExistentes.ToList();
                    nuevosTelef = telefonoExistentesList;
                    nuevosTelef.Add(new Telefono(tipoTef, numeroTef));
                }
                else
                {
                    nuevosTelef.Add(new Telefono(tipoTef, numeroTef));
                }

                cliente.Telefonos = nuevosTelef.ToArray();

                var laConexion = new Clientes();
                laConexion.UpdateClientes("proyectoDb", "clientes_bson", id,cliente);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var laConexion = new Clientes();
            Cliente cliente = laConexion.FindClienteDocument("proyectoDb", "clientes_bson", id);
                
            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        public ActionResult Delete(int id,Cliente cliente)
        {
            try
            {
                
                var laConexion = new Clientes();
                laConexion.DeleteClientesDocument("proyectoDb", "clientes_bson",id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto_NoSQL/Proyecto_NoSQL/Controllers/CobroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto.Logic.Conexion;
using Proyecto.Logic.Utilitarias;
using Proyecto.Model.MisModelos;

namespace Proyecto_NoSQL.Controllers
{
    public class CobroController : Controller
    {
        // GET: Cobro
        public ActionResult Index()
        {


            return View();
        }
        [HttpPost]
        public ActionResult Index(Cobro factura)
        {
            try
            {

                var laConexion = new Clientes();
                Cliente cliente = laConexion.FindClienteDocument("proyectoDb", "clientes_bson", factura.cedula);


                if (cliente != null)
                {
                    double impuestos = (factura.iva / 100) * factura.valor;
                    double total = factura.valor + impuestos;
                    double cambio =  factura.montoCancelado- total ;
                    CorreoElectronico.EnviarEmail(cliente.Nombre + " " + cliente.PrimerApellido + " " + cliente.SegundoApellido, cliente.Email,
                        "Información de factura:\n" +
                        "Cédula:" + cliente.Cedula + "\n" +
                        "Descripción: " + factura.descripcion + "\n" +
                        "Costo del sercio= ¢" + factura.valor + "\n" +
                       "IVA(" + factura.iva +"%) = ¢" + impuestos + "\n" +
                       "Total= ¢" +  total + "\n" +
                       "Método de Pago: ¢" + factura.medioPago + "\n" +
                       "Monto Cancelado= ¢" + factura.montoCancelado + "\n" +
                       "Cambio= ¢" + cambio
                       );
         

                   // ViewBag.mensaje = "Nueva factura";
                    return RedirectToAction("Index");     
                }
                else
                {
                    ViewBag.mensaje = "Usuario no registrado";
                    return View(factura);
                }

               
            }
            catch
            {
                return View(factura);
            }
        }

    }
}

Proyecto_NoSQL/Proyecto_NoSQL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proyecto_NoSQL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Proyecto_NoSQL/Proyecto_NoSQL/Views/Cliente/Create.cshtml
@model Proyecto.Model.MisModelos.Cliente

@{
    ViewBag.Title = "Agregar Cliente";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tipo teléfono</label>
            <input class="form-control" type="text" name="tipoTef" value="" />
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Número Teléfono</label>
            <input class="form-control" type="text" name="numeroTef" value="" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Pais, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Pais, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Canton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Canton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Canton, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
</body>
</html>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Cliente/Delete.cshtml
@model Proyecto.Model.MisModelos.Cliente

@{
    ViewBag.Title = "Eliminar Cliente";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Esta seguro de eliminar este Cliente?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Cedula)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cedula)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PrimerApellido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PrimerApellido)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SegundoApellido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SegundoApellido)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Pais)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Pais)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Provincia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Provincia)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Canton)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Canton)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Distrito)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Distrito)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Cliente/Details.cshtml
@model Proyecto.Model.MisModelos.Cliente

@{
    ViewBag.Title = "";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>

<body>
    <div>
        <h4>Cliente</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>

                @Html.DisplayNameFor(model => model.Cedula)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cedula)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PrimerApellido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PrimerApellido)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SegundoApellido)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SegundoApellido)
            </dd>

            @foreach (var telefono in Model.Telefonos)
            {
                <dt>
                    Tipo número de teléfono
                </dt>

                <dd>
                    @telefono.Tipo
                </dd>
                <dt>
                    Número
                </dt>

                <dd>
                    @telefono.Numero
                </dd>

            }



            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Pais)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Pais)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Provincia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Provincia)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Canton)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Canton)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Direccion.Distrito)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Direccion.Distrito)
            </dd>

        </dl>
    </div>
    <p>

        @Html.ActionLink("Edit", "Edit", new { id = Model.Cedula }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Cliente/Edit.cshtml
@model Proyecto.Model.MisModelos.Cliente


    @{
        ViewBag.Title = "Editar Cliente";
    }
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimerApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrimerApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SegundoApellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SegundoApellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tipo teléfono</label>
            <input class="form-control" type="text" name="tipoTef" value="" />
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Número Teléfono</label>
            <input class="form-control" type="text" name="numeroTef" value="" />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Pais, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Pais, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Canton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Canton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Canton, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Direccion.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Cliente/Index.cshtml
@model IEnumerable<Proyecto.Model.MisModelos.Cliente>

@{
    ViewBag.Title = "Clientes";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimerApellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SegundoApellido)
            </th>
            <th>
                Tipo télefono
            </th>
            <th>
               Número teléfono
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Dirección
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimerApellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SegundoApellido)
            </td>
            <td>

                @{
                    String tipoTelef = "-";
                    String numero = "-";
                    if (item.Telefonos != null)
                    {
                        tipoTelef = item.Telefonos.First().Tipo.ToString();
                        numero = item.Telefonos.First().Numero.ToString();
                    }
                }

                @tipoTelef
            </td>
            <td>
               @numero
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion.Provincia)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Cedula }) |
                @Html.ActionLink("Details", "Details", new { id = item.Cedula }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Cedula })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}

<div class="jumbotron">
    <h1>Hoteleria Mongo</h1>
    <p class="lead">No SQL</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Conneccion MongoDB Asp.net  MVC  </h2>
    </div>
</div>

Proyecto_NoSQL/Proyecto_NoSQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MongoDB NoSQL</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NoSQL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Cobro servicio", "Index", "Cobro")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bases de Datos NoSQL</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>